meta_product_name: "firework.vn"
meta_separator: "·"
meta_title: "Nền tảng giúp bạn có được công việc mơ ước"
meta_description: "Firework là nền tảng chia sẻ các thông tin trong tìm kiếm việc làm như review công ty, kinh nghiệm phỏng vấn, bài test phỏng vấn,... Giúp bạn có sự chuẩn bị tốt nhất trên con đường tìm kiếm công việc mơ ước."
meta_image: "logo_offical.png"
meta_key_word: "Review công ty, việc làm, phỏng vấn, chia sẻ kinh nghiệm, tìm việc"
twitter_account: "@dungnguyen_93"   # required for Twitter Cards