meta_product_name: "Firework"
meta_separator: "|"
meta_title: "Review công ty, kinh nghiệm phỏng vấn, việc làm mới nhất"
meta_description: "Firework là nền tảng chia sẻ thông tin trong tìm kiếm việc làm như review công ty, kinh nghiệm tìm việc, bài test phỏng vấn, chế độ lương, tin tuyển dụng mới nhất..."
meta_image: "favicon.ico"
meta_key_word: "Review công ty, việc làm, phỏng vấn, chia sẻ kinh nghiệm, tìm việc, lương, câu hỏi phỏng vấn"
twitter_account: "@dungnguyen_93"   # required for Twitter Cards
meta_robots: "noindex, nofollow"
