development:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - default
# :schedule:
#   scrap_woker:
#     #      s m h d m w
#     # cron: '47 16 * * *'
#     every: 12 hours
#     class: ScrapWorker