development:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - default
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:schedule:
  scrap_woker:
    #      s m h d m w
    # cron: '47 16 * * *'
    every: 5m
    class: ScrapWorker