default: &default
  height: 500
  menubar: true
  selector: textarea
  menubar: file edit view insert format tools table tc help
  toolbar:
    - undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor permanentpen formatpainter removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | a11ycheck ltr rtl | showcomments addcomment
  plugins:
    - print preview importcss searchreplace autolink autosave save directionality visualblocks visualchars fullscreen image autoresize
    - link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount 
    - imagetools textpattern noneditable help charmap quickbars emoticons
  skin: 
    - oxide
  icons:
    - bootstrap
  autosave_ask_before_unload: true
  autosave_interval: 30s
  autosave_restore_when_empty: false
  autosave_retention: 2m
  image_advtab: true
  image_caption: true
  quickbars_selection_toolbar: bold italic | quicklink h2 h3 blockquote quickimage quicktable
  noneditable_noneditable_class: mceNonEditable
  toolbar_mode: sliding
  tinycomments_mode: embedded
  contextmenu: link image imagetools table configure
  a11y_advanced_options: true
  branding: false

# Medium config editor
medium:
  <<: *default
  height: 333
  menubar: false
  toolbar:
    - bold | italic | underline | numlist | bullist | forecolor | backcolor | charmap | emoticons | image | link | fullscreen | preview | undo | redo
  plugins:
    - autolink autosave emoticons fullscreen charmap
    - insertdatetime media table paste code help wordcount
    - advlist autolink lists link image charmap print preview anchor
  branding: false

# Mini config editor
mini:
  <<: *default
  height: 200
  menubar: false
  toolbar:
    - bold italic | emoticons | bullist numlist | undo redo
  plugins:
    - autolink autosave emoticons
    - insertdatetime media table paste code help wordcount
    - advlist autolink lists link image charmap print preview anchor
  branding: false